In [2]:
import pandas as pd
print("Pandas version:", pd.__version__)

Pandas version: 2.2.3

In [5]:
students = {
    "Roll no.": [101, 102, 103, 104, 105],
    "Name": ["A", "B", "C", "D", "E"],
    "Department": ["CS", "DS", "IT", "CS", "IT"],
    "Age": [18, 19, 20, 21, 22],
    "Marks": [90, 80, 70, 60, 50]
}

df = pd.DataFrame(students)
print(df)

   Roll no. Name Department  Age  Marks
0       101    A         CS   18     90
1       102    B         DS   19     80
2       103    C         IT   20     70
3       104    D         CS   21     60
4       105    E         IT   22     50

In [6]:
# selecting any particular column
print(df['Name'])

0    A
1    B
2    C
3    D
4    E
Name: Name, dtype: object

In [9]:
df[["Name","Marks"]]

  Name  Marks
0    A     90
1    B     80
2    C     70
3    D     60
4    E     50

In [10]:
df.loc[2]

Roll no.      103
Name            C
Department     IT
Age            20
Marks          70
Name: 2, dtype: object

In [11]:
df.loc[2, "Marks"]

np.int64(70)

In [12]:
df.iloc[4]

Roll no.      105
Name            E
Department     IT
Age            22
Marks          50
Name: 4, dtype: object

In [14]:
df.iloc[4,[4]]

Marks    50
Name: 4, dtype: object

In [16]:
df[df["Marks"]>=70]

   Roll no. Name Department  Age  Marks
0       101    A         CS   18     90
1       102    B         DS   19     80
2       103    C         IT   20     70

In [17]:
df[(df["Marks"]>=70) & (df["Age"]>=20)]

   Roll no. Name Department  Age  Marks
2       103    C         IT   20     70

In [19]:
df.sort_values("Marks")

   Roll no. Name Department  Age  Marks
4       105    E         IT   22     50
3       104    D         CS   21     60
2       103    C         IT   20     70
1       102    B         DS   19     80
0       101    A         CS   18     90

In [18]:
df.sort_values("Marks", ascending=False)

   Roll no. Name Department  Age  Marks
0       101    A         CS   18     90
1       102    B         DS   19     80
2       103    C         IT   20     70
3       104    D         CS   21     60
4       105    E         IT   22     50

In [20]:
df["Result"]="Pass"

In [21]:
df.loc[df["Marks"]<70,"Result"]="Needs Improvement"

In [22]:
df

   Roll no. Name Department  Age  Marks             Result
0       101    A         CS   18     90               Pass
1       102    B         DS   19     80               Pass
2       103    C         IT   20     70               Pass
3       104    D         CS   21     60  Needs Improvement
4       105    E         IT   22     50  Needs Improvement

In [23]:
import numpy as np
df.loc[2,"Marks"]=np.nan
df.loc[4,"Age"]=np.nan
df

   Roll no. Name Department   Age  Marks             Result
0       101    A         CS  18.0   90.0               Pass
1       102    B         DS  19.0   80.0               Pass
2       103    C         IT  20.0    NaN               Pass
3       104    D         CS  21.0   60.0  Needs Improvement
4       105    E         IT   NaN   50.0  Needs Improvement

In [25]:
df.isnull()

   Roll no.   Name  Department    Age  Marks  Result
0     False  False       False  False  False   False
1     False  False       False  False  False   False
2     False  False       False  False   True   False
3     False  False       False  False  False   False
4     False  False       False   True  False   False

In [26]:
df.isnull().sum()

Roll no.      0
Name          0
Department    0
Age           1
Marks         1
Result        0
dtype: int64

In [27]:
df.fillna(0)

   Roll no. Name Department   Age  Marks             Result
0       101    A         CS  18.0   90.0               Pass
1       102    B         DS  19.0   80.0               Pass
2       103    C         IT  20.0    0.0               Pass
3       104    D         CS  21.0   60.0  Needs Improvement
4       105    E         IT   0.0   50.0  Needs Improvement

In [28]:
df.dropna()

   Roll no. Name Department   Age  Marks             Result
0       101    A         CS  18.0   90.0               Pass
1       102    B         DS  19.0   80.0               Pass
3       104    D         CS  21.0   60.0  Needs Improvement

In [29]:
df["Marks"].fillna(df["Marks"].mean())

0    90.0
1    80.0
2    70.0
3    60.0
4    50.0
Name: Marks, dtype: float64